apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: safety-demo
  labels:
    app: safety-api
spec:
  type: LoadBalancer
  selector:
    app: safety-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
